controller:
  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
    ports:
      http: 80
      https: 443
    targetPorts:
      http: http
      https: https
  metrics:
    enabled: true
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "10254"
