# Global settings to use Longhorn for all persistence
global:
  clusterDomain: cluster.local
  dnsService: rke2-coredns-rke2-coredns

# Alloy Collector (Scraping Node Metrics)
alloy:
  config: |
    prometheus.exporter.unix "node_stats" { }
    
    prometheus.scrape "metrics_integrations" {
      targets    = prometheus.exporter.unix.node_stats.targets
      forward_to = [prometheus.remote_write.mimir.receiver]
    }

    prometheus.remote_write "mimir" {
      endpoint {
        url = "http://lgtm-stack-mimir-nginx.observability.svc:80/api/v1/push"
      }
    }