# Global settings to use Longhorn for all persistence
global:
  clusterDomain: cluster.local
  dnsService: rke2-coredns-rke2-coredns

loki:
  enabled: true
  loki:
    auth_enabled: false
    commonConfig:
      replication_factor: 1
    storage:
      type: filesystem # Loki uses the PVC to store chunks here
  gateway:
    enabled: true
  # This creates the PVCs using Longhorn
  minio:
    enabled: true # Loki distributed often uses a local minio for simplicity
    persistence:
      storageClass: "longhorn"
      size: 3Gi
  singleBinary:
    persistence:
      enabled: true
      storageClass: "longhorn"
      size: 3Gi

mimir:
  enabled: true
  gateway:
    enabled: true
  # Mimir components that need disk space
  ingester:
    persistentVolume:
      storageClass: "longhorn"
      size: 3Gi
  store_gateway:
    persistentVolume:
      storageClass: "longhorn"
      size: 3Gi

grafana:
  enabled: true
  persistence:
    enabled: true
    storageClass: "longhorn"
    size: 3Gi
  admin:
    existingSecret: "grafana-admin-credentials"
    userKey: "admin-user"
    passwordKey: "admin-password"
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Mimir
          type: prometheus
          url: http://lgtm-stack-mimir-nginx.observability.svc:80/prometheus
          isDefault: true
        - name: Loki
          type: loki
          url: http://lgtm-stack-loki-gateway.observability.svc:80