# Longhorn values file
ingress:
  enabled: true
  ingressClassName: nginx
  host: longhorn.meiot.site
  path: /
  pathType: ImplementationSpecific

preUpgradeChecker:
  jobEnabled: false

persistence:
  defaultClassReplicaCount: 2

defaultSettings:
  defaultReplicaCount: "2"
